"""
Merchant adverse-media intel — an optional, external, escalate-only signal.

WHY THIS EXISTS
---------------
Every input to the merchant risk signal in code/risk_signals.py is internal
and backward-looking: chargeback_rate_90d and prior_contest_win_rate. Both
are consequences. A merchant only trips is_merchant_repeat_pattern() after
they have already produced ninety days of chargebacks and lost the contests
that followed.

For an acquirer that is too late. Under Visa's VAMP the fine is levied per
dispute once the portfolio ratio crosses threshold, so by the time internal
data names a merchant, the money is already gone.

Public complaints are the leading indicator. Customers post about a merchant
who stopped shipping weeks before those customers get around to calling their
bank. This module reads that signal off the open web.

WHY IT IS NOT IN THE PIPELINE
-----------------------------
code/main.py does not import this file, and a test asserts that it never
will. Two reasons:

  1. Reproducibility. The committed held-out numbers (0 FP, 0 FN, 76%
     coverage) can be recomputed from the repo alone. A live search call in
     the scoring path would make every run depend on what Google returned
     that afternoon, and the evaluation would stop being a measurement.

  2. Provenance. Everything in the pipeline is either computed from the case
     file or generated by the model under controlled conditions. Search
     results are neither. They belong in the operator's console, next to a
     human, not inside an automated decision.

WHY IT CAN ONLY ESCALATE
------------------------
Web results about a business are unverifiable, gameable by a competitor with
an afternoon and a few sock puppets, and ambiguous whenever two companies
share a name. A signal with those properties has no business clearing a
merchant.

So the contract is one-directional and enforced in code: this module may move
a case toward manual_review and may never move one away from it. It cannot
turn a review into a contest, it cannot raise a confidence score, and it
cannot mark anything as safe. The worst a false positive can do is buy a case
twelve minutes of human attention. See escalate_only().

It also never labels a business. It reports how many complaint-shaped results
exist and links every one of them, because the honest output of a keyword
search is evidence for a person to read, not a verdict about a company.
"""

import hashlib
import json
import os
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

SERPAPI_ENDPOINT = "https://serpapi.com/search.json"

CACHE_DIR = Path(__file__).parent.parent / ".cache" / "merchant_intel"

# A day. Complaint volume moves over weeks, so re-querying per page load would
# spend the quota to watch a number not change.
CACHE_TTL_SECONDS = 24 * 60 * 60

DEFAULT_TIMEOUT_SECONDS = 12

# Deliberately coarse. The useful question is "is anyone complaining", not
# "how many exactly" — search result counts are far too noisy to support a
# finer scale, and a precise-looking number invites false confidence.
THRESHOLD_ELEVATED = 5
THRESHOLD_SOME = 1

# Sites where an Indian consumer actually goes to complain about a merchant.
# Presence here is what separates a complaint from a news article that merely
# contains the word "refund".
COMPLAINT_DOMAINS = (
    "consumercomplaints.in",
    "complaintboard.in",
    "mouthshut.com",
    "trustpilot.com",
    "reddit.com",
    "quora.com",
    "consumerhelpline.gov.in",
    "grahakseva.com",
    "ripoffreport.com",
    "sitejabber.com",
)

COMPLAINT_TERMS = (
    "complaint", "scam", "fraud", "cheated", "not delivered", "never received",
    "no refund", "refund not", "fake", "duped", "money not returned",
)


class MerchantIntelUnavailable(Exception):
    """Raised for a configuration or transport failure. Never raised because
    a merchant looks bad — that is a result, not an error."""


def has_api_key(env=None):
    env = os.environ if env is None else env
    return bool((env.get("SERPAPI_KEY") or "").strip())


def _cache_path(query):
    digest = hashlib.sha256(query.encode("utf-8")).hexdigest()
    return CACHE_DIR / f"{digest}.json"


def _cache_get(query):
    path = _cache_path(query)
    if not path.exists():
        return None
    try:
        blob = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    if time.time() - blob.get("fetched_at", 0) > CACHE_TTL_SECONDS:
        return None
    return blob.get("payload")


def _cache_put(query, payload):
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    _cache_path(query).write_text(
        json.dumps({"fetched_at": time.time(), "payload": payload}, ensure_ascii=False),
        encoding="utf-8",
    )


def build_query(merchant_name):
    """The search that finds complaints without finding the merchant's own
    marketing. Quoting the name keeps two-word brands from matching every page
    containing either word."""
    name = (merchant_name or "").strip()
    if not name:
        raise MerchantIntelUnavailable("merchant name is empty")
    terms = " OR ".join(f'"{t}"' for t in ("complaint", "scam", "fraud", "not delivered", "refund not received"))
    return f'"{name}" ({terms})'


def _fetch(query, api_key, timeout=DEFAULT_TIMEOUT_SECONDS, opener=None):
    """One SerpAPI call. urllib rather than requests, because requests is not
    a dependency of this project and adding one for a single GET is not worth
    the install surface."""
    params = urllib.parse.urlencode({
        "engine": "google",
        "q": query,
        "api_key": api_key,
        "num": 20,
        "hl": "en",
        "gl": "in",   # Indian results — this is an Indian payments product
    })
    url = f"{SERPAPI_ENDPOINT}?{params}"
    request = urllib.request.Request(url, headers={"User-Agent": "AEDI/1.0"})
    try:
        _open = opener or urllib.request.urlopen
        with _open(request, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        detail = ""
        try:
            detail = json.loads(e.read().decode("utf-8")).get("error", "")
        except Exception:
            pass
        if e.code in (401, 403):
            raise MerchantIntelUnavailable(
                f"SerpAPI rejected the key (HTTP {e.code}). {detail}".strip()) from e
        if e.code == 429:
            raise MerchantIntelUnavailable(
                "SerpAPI monthly search quota is exhausted.") from e
        raise MerchantIntelUnavailable(f"SerpAPI returned HTTP {e.code}. {detail}".strip()) from e
    except urllib.error.URLError as e:
        raise MerchantIntelUnavailable(f"could not reach SerpAPI: {e.reason}") from e
    except (json.JSONDecodeError, ValueError) as e:
        raise MerchantIntelUnavailable(f"SerpAPI returned something that was not JSON: {e}") from e


def _domain_of(link):
    try:
        return (urllib.parse.urlparse(link or "").netloc or "").lower().removeprefix("www.")
    except ValueError:
        return ""


def classify_results(organic_results):
    """Split raw results into complaint-shaped and everything else.

    A result counts as a complaint when it is on a consumer-complaint site OR
    its title/snippet carries a complaint term. Two weak tests joined by OR
    rather than one strict test, because a complaint on a forum often does not
    use any of the keywords, and a keyword hit off-forum is often a news
    article about the merchant rather than a customer with a grievance. Both
    kinds are worth a human's eye; neither is worth an automated decision.
    """
    hits, others = [], []
    for r in organic_results or []:
        link = r.get("link", "")
        domain = _domain_of(link)
        text = f"{r.get('title', '')} {r.get('snippet', '')}".lower()
        on_complaint_site = any(domain.endswith(d) for d in COMPLAINT_DOMAINS)
        has_term = any(t in text for t in COMPLAINT_TERMS)
        record = {
            "title": r.get("title", ""),
            "link": link,
            "domain": domain,
            "snippet": r.get("snippet", ""),
            "on_complaint_site": on_complaint_site,
            "matched_terms": sorted({t for t in COMPLAINT_TERMS if t in text}),
        }
        (hits if (on_complaint_site or has_term) else others).append(record)
    return hits, others


def signal_for(n_hits):
    """Three buckets, on purpose. See THRESHOLD_* above."""
    if n_hits >= THRESHOLD_ELEVATED:
        return "elevated"
    if n_hits >= THRESHOLD_SOME:
        return "some"
    return "clear"


def look_up(merchant_name, env=None, opener=None, use_cache=True):
    """Returns a result dict. Raises MerchantIntelUnavailable only for
    configuration or transport problems, never for what was found."""
    env = os.environ if env is None else env
    api_key = (env.get("SERPAPI_KEY") or "").strip()
    if not api_key:
        raise MerchantIntelUnavailable(
            "no SERPAPI_KEY in .env — add one from https://serpapi.com to enable this panel")

    query = build_query(merchant_name)

    cached = _cache_get(query) if use_cache else None
    payload = cached if cached is not None else _fetch(query, api_key, opener=opener)
    if cached is None and use_cache:
        _cache_put(query, payload)

    if isinstance(payload, dict) and payload.get("error"):
        raise MerchantIntelUnavailable(f"SerpAPI: {payload['error']}")

    hits, others = classify_results((payload or {}).get("organic_results"))
    signal = signal_for(len(hits))
    return {
        "merchant_name": merchant_name,
        "query": query,
        "signal": signal,
        "n_complaint_results": len(hits),
        "n_other_results": len(others),
        "results": hits[:10],
        "cached": cached is not None,
        # Restated in the payload so a consumer of this API cannot forget it.
        "escalate_only": True,
        "advisory": (
            "Unverified public search results. This signal may route a case to a "
            "human reviewer and may never clear one, decide one, or label a business."
        ),
    }


def escalate_only(decision, signal):
    """The one-directional contract, enforced rather than documented.

    An elevated signal turns an automated decision into manual_review. Every
    other combination is returned untouched — in particular, a manual_review
    is never converted into anything else, no matter how clean the search
    came back.
    """
    if signal == "elevated" and decision in ("contest", "accept_liability"):
        return "manual_review", True
    return decision, False
